Identity table
HedvigInsurance/member-registry-service pull request #454
Opened 2020-12-23 16:18 UTC by FredrikAreschoug

2021-01-12 15:25 UTC, johantjellden commented on member-service/src/main/java/com/hedvig/memberservice/commands/ZignSecSuccessfulAuthenticationCommand.kt
> +    val provideJsonResponse: String,
```suggestion
    val providerJsonResponse: String,
```

2021-01-12 15:27 UTC, johantjellden commented on member-service/src/main/java/com/hedvig/memberservice/identity/IdentityEventListener.kt
> +    private fun paresLastNameFromZignSecJson(json: String): String? =
```suggestion
    private fun parseLastNameFromZignSecJson(json: String): String? =
```

2021-01-12 15:27 UTC, johantjellden commented on member-service/src/main/java/com/hedvig/memberservice/identity/IdentityEventListener.kt
> +    private fun paresFirstNameFromZignSecJson(json: String): String? =
```suggestion
    private fun parseFirstNameFromZignSecJson(json: String): String? =
```
:)

2021-01-12 15:33 UTC, johantjellden commented on member-service/src/main/java/com/hedvig/memberservice/identity/IdentityEventListener.kt
> +        val lastName: String?
Should we associate `ZignSecJson` and `ZignSecJsonIdentity`  to the event somehow? Perhaps on the event or maybe as an abstract class or interface that the events that includes this json could implement.

2021-01-12 15:45 UTC, vonElfvin reviewed
Neat solution! Nice to not have to touch more than this :)

2021-01-12 15:45 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/aggregates/MemberAggregate.kt
> +        if (!isValidJSON(command.provideJsonResponse)) throw RuntimeException("Invalid json from provider")
Does this happen often? 😄

2021-01-12 15:45 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/identity/repository/IdentityEntity.kt
> +    val memberId: Long,
Not entirely sure about this but I think we prefer having memberId as a String but incorrectly made it into a Long in member-service. Don't know for sure though
```suggestion
    val memberId: String,
```

2021-01-12 15:45 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/web/IdentityController.kt
> +}
Do we need the identity in hope or a just a boolean if they are identified? 🤔

2021-01-12 15:45 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/events/ZignSecSuccessfulAuthenticationEvent.kt
> +    }
Or is the method itself important maybe?

2021-01-12 15:45 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/identity/IdentityEventListener.kt
> +    fun on(event: NorwegianMemberSignedEvent) {
Add one for danish members while we're here? And what about Swedish members? So we don't have to replay all the events if we enable this in Sweden at some point.

2021-01-12 15:47 UTC, FredrikAreschoug commented on member-service/src/main/java/com/hedvig/memberservice/aggregates/MemberAggregate.kt
> +        if (!isValidJSON(command.provideJsonResponse)) throw RuntimeException("Invalid json from provider")
No never but it's an event And I rather have a valid json than jibberish :slightly_smiling_face:

2021-01-12 15:52 UTC, FredrikAreschoug commented on member-service/src/main/java/com/hedvig/memberservice/events/ZignSecSuccessfulAuthenticationEvent.kt
> +    }
Yeah maybe this is a bit to much but I think it's good to know how they were identified and not just that they where :slightly_smiling_face:

2021-01-12 16:06 UTC, FredrikAreschoug commented on member-service/src/main/java/com/hedvig/memberservice/web/IdentityController.kt
> +}
I think we should have it and use it for sanction :slightly_smiling_face:

2021-01-12 16:07 UTC, FredrikAreschoug commented on member-service/src/main/java/com/hedvig/memberservice/identity/IdentityEventListener.kt
> +    fun on(event: NorwegianMemberSignedEvent) {
Let's not add more to this because I know we will need to create an event for Swedish authentication. So I rather keep this small un till it is tested in Norway.

2021-01-13 12:56 UTC, vonElfvin submitted a review, later dismissed
N1️⃣

2021-01-13 12:56 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/identity/repository/IdentityEntity.kt
> +            if (newIdentityEntity.memberId != oldIdentityEntity.memberId) {
Maybe? 🤔 
```suggestion
        fun hasNewOrMoreNewInfo(newIdentityEntity: IdentityEntity): Boolean {
            if (this.memberId != newIdentityEntity.memberId) {
```

2021-01-13 14:32 UTC, vonElfvin submitted a review, later dismissed

2021-01-15 08:59 UTC, vonElfvin requested changes
The event "backfill" looks off to me, could have discussion about it if you like. Maybe I'm missing something.

2021-01-15 08:59 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/config/AxonConfig.java
> +          "BackfillMemberIdentifiedEventNorway",
Wouldn't call a processing group "Backfill" and probably not even "Event" or "Norway" unless we have a table that is specific for that event in that market. Do you think you'll have multiple? Otherwise "MemberIdentity" or similar would suffice

2021-01-15 08:59 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/aggregates/MemberAggregate.kt
> +                /* TODO: Uncomment this when removing BackfillMemberIdentifiedEventNorwayListener
Since events always end up at the end of the event log I don't think we need to comment anything out really.

2021-01-15 08:59 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/backfill/BackfillMemberIdentifiedEventNorwayListener.kt
> + */
Why not just have it running?

2021-01-15 08:59 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/backfill/BackfillMemberIdentifiedEventNorwayListener.kt
> +class BackfillMemberIdentifiedEventNorwayListener(
Why not just have it running with a tail token?

2021-01-15 08:59 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/events/MemberIdentifiedEvent.kt
> +    }
```suggestion
    enum class Nationality {
        SWEDEN, 
        NORWAY,
        DENMARK
    }
```

2021-01-15 08:59 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/identity/IdentityEventListener.kt
> +                    MemberIdentifiedEvent.Nationality.DENMARK -> Nationality.DENMARK
Feels like a enum like "Nationality" could live in a library somewhere. For example use CountryCode that is used quite a lot already.

2021-01-15 09:03 UTC, FredrikAreschoug commented on member-service/src/main/java/com/hedvig/memberservice/backfill/BackfillMemberIdentifiedEventNorwayListener.kt
> + */
Because I think it makes more sense applying it in the aggregate

2021-01-15 09:04 UTC, FredrikAreschoug commented on member-service/src/main/java/com/hedvig/memberservice/backfill/BackfillMemberIdentifiedEventNorwayListener.kt
> +class BackfillMemberIdentifiedEventNorwayListener(
Because I think it is clear long term to remove this

2021-01-15 09:06 UTC, FredrikAreschoug commented on member-service/src/main/java/com/hedvig/memberservice/identity/IdentityEventListener.kt
> +                    MemberIdentifiedEvent.Nationality.DENMARK -> Nationality.DENMARK
I rather map one time too many than using the event instance in the wrong place

2021-01-15 12:28 UTC, vonElfvin submitted a review, later dismissed

2021-01-15 12:28 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/identity/IdentityEventListener.kt
> +                    MemberIdentifiedEvent.Nationality.DENMARK -> Nationality.DENMARK
I was thinking scrapping "Nationality" entirely from all locations and use CountryCode instead. That way we'll have a Enum that we don't have to maintain that we don't have to update and map. But I don't know what's best

2021-01-15 12:41 UTC, johantjellden approved these changes
💯

2021-01-15 12:45 UTC, merged