Auth module
HedvigInsurance/member-registry-service pull request #489
Opened 2021-04-15 21:52 UTC by niho

# Jira Issue: [ME-83]

## What?
- ME-83: Move auth system to its own module
- ME-82: Delete user on `MemberCancellationEvent`

## Why?
- Will make the separation between the auth system and member-service cleaner and encourage us (long term) to eventually move the code to its own micro-service and (short term) improve the modularity of member-service.

2021-04-16 14:24 UTC, niho commented
The build in Codefresh fails, but I suspect that is because of a cache issue that I'm unable to solve. The build works fine for me on my local machine, doing a full docker build with no cache.

I suppose the only way to get around the failed build in Codefresh is to merge with admin privileges and simply ignore the failed check. My assumption is that it will work fine building on a new branch (i.e., master when merged).

2021-04-19 07:28 UTC, bystam requested changes
Looks nice - but I had some thoughts and comments. And at least one or two things I think need be addressed.

2021-04-19 07:28 UTC, bystam commented on auth/pom.xml
> +        </dependency>
I wonder if we can tag the h2-database as `<scope>test</scope>`?

2021-04-19 07:28 UTC, bystam commented on auth/src/main/kotlin/com/hedvig/auth/services/UserService.kt
> + * @author Fredrik Byström <fredrik.bystrom@hedvig.com>
"Byström" is not my name 🙃 

```suggestion
 * @author Fredrik Tõnisson-Bystam <fredrik.bystam@hedvig.com>
```

2021-04-19 07:28 UTC, bystam commented on auth/src/main/resources/application.properties
> +
I think this file could be deleted. It's an alternative format to `application.yml`.

2021-04-19 07:28 UTC, bystam commented on member-service/src/test/resources/application.yml
> +http.client.ssl.key-store: /Users/niklas/hedvig/dev-env/secrets/keyStore.jks
`/Users/niklas/` probably isn't right. Don't we use the `DEV_ENV_DIR` environment variable here usually? Curious how/if that is set up to work at all when running on the CI.

2021-04-19 07:28 UTC, bystam commented on member-service/src/test/resources/application.yml
> +trustpilot.oauth.password: test
I think these trustpilot ones can be omitted. I refactored these to only be required if `trustpilot.customerio-review-links-enabled` is set to `true`.

2021-04-19 07:28 UTC, bystam commented on member-service/src/test/resources/application.yml
> +http.client.ssl.key-store: /Users/niklas/hedvig/dev-env/secrets/keyStore.jks
This is probably why the branch fails to build on Codefresh.

2021-04-19 08:05 UTC, vonElfvin reviewed
Really nice step towards decoupling authentication, especially nice that we take the time 🥳 

I added some thoughts that might be worth considering 🤷

2021-04-19 08:05 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/users/MemberCancellationEventHandler.kt
> +    }
I think this could be a legacy event for when we cancelled a member rather than an insurance

2021-04-19 08:05 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/config/AxonConfig.java
> +          "com.hedvig.memberservice.users",
I think this is the default naming and singleThreadedProcessing is the default processor so if you want you can remove this, if we think we'd like to config it in the future we can of course keep it

2021-04-19 08:05 UTC, vonElfvin commented on auth/src/main/kotlin/com/hedvig/auth/services/UserService.kt
> +     */
I think comments as these allow for automatic generation of documentation right? That would be cool to have

2021-04-19 08:25 UTC, bystam commented on auth/src/main/kotlin/com/hedvig/auth/services/UserService.kt
> +     */
I personally sort of disagree with the "don't write comments" approach, and find it a tad... extremist. Having good names in the code is good, but there are things that I think cannot be expressed with good names.

Part of it is the fact that names are subjective - the fact that they are obvious to one person might not be true for someone else. A longer piece of documentation can usually find ways to bridge the gap by explaining more closely.

And I feel there's an overlap between the process of writing documentation and the process of writing for instance RFCs. Sometimes, when you try to document your system/API, you realise that maybe it's actually quite hard to explain. And that can lead you towards evolving your own thinking around what you're currently building.

There are also things you can explain using documentation that you simply can't with code. For instance, the intent behind a system and how you imagine it evolving. Maybe there are ways in which you wish to express that system `A` should never depend on system `B` for purposes of decoupling. It's not very very nice to express that through names like `AthatDoesntDependOnBService`- but system/service documentation does this beautifully.

> Historically we've decided to avoid comments at Hedvig since they become hard to keep up to date.

That in turn becomes a discussion whether partial documentation is better or worse than no documentation at all. This is also subjective. I find that good, but incomplete documentation is very helpful when getting to know new things. If we regularly find our documentation to evolve into being **explicitly misleading**, then I am not entirely sure that's a 100% documentation issue. Then we could arguably start asking ourselves why our things often change to make past assumptions/contracts invalid. That would arguably violate the open/closed principle.

---- 

Of course, there's also levels to it. My general approach is that if I'm building something that is quite fundamental to a service and might be the concern of several other users, then I think documentation is helpful. If I'm writing something very "high level", like an end user UI or such, I don't find it super necessary or even redundant.

In this context, that to me means that I think it's nice to document core data models (`User`) and their primary gateways to interaction (`UserService`). But if we have some very rudimentary RESTy endpoints, then maybe it doesn't help to spell out `/** Get User by ID */`.

2021-04-19 08:26 UTC, bystam commented on member-service/src/main/java/com/hedvig/config/AxonConfig.java
> +          "com.hedvig.memberservice.users",
The reason we added this was because I think I recall that the current version of Axon (not the latest one) actually makes the default event processor type a **subscribing** one, and we thought that tracking made way more sense.

2021-04-19 09:34 UTC, niho commented on auth/src/main/kotlin/com/hedvig/auth/services/UserService.kt
> +     */
It's of course a tradeoff. The approach that I have used for many years and that I think is fairly well established in the engineering community (at least in OSS) is to *always* document your **public** API and leave documentation of internal stuff to be more ad-hoc.

That approach has many benefits:
- It forces you to think clearly about boundaries in your code. What is your intended public API and what is internal implementation detail?
- It makes your public API less likely to evolve (a good thing) and thus more likely to well designed.
- At the same time it makes your internal implementation *more* likely to evolve and change (which is also a good thing).
- And as @bystam mentions, writing documentation forces you to think clearly about what you are really doing and makes your thought process clear to anyone that needs to interact with your code in the future.

2021-04-19 09:41 UTC, niho commented on member-service/src/main/java/com/hedvig/config/SSLConfig.java
> +      }
I was trying to make `@SpringBootTest` work properly. This is just a remnant of that.

2021-04-19 09:44 UTC, niho commented on auth/mvnw.cmd
> +exit /B %ERROR_CODE%
Those got added by Intellij, so no intent from my part. But I guess it doesn't hurt to think about the modules as more or less self-contained projects?

2021-04-19 09:48 UTC, niho commented on member-service/src/test/resources/application.yml
> +http.client.ssl.key-store: /Users/niklas/hedvig/dev-env/secrets/keyStore.jks
This got left in by accident when I tried to get `@SpringBootTest` to work.

2021-04-19 09:50 UTC, niho commented on auth/src/main/kotlin/com/hedvig/auth/models/SwedishBankIdCredential.kt
> -    val createdAt: Instant = Instant.now()
The hack to set `createdAt` timestamp manually was only needed for the initial import. This changes it back to use a proper `@CreationTimestamp`.

2021-04-19 11:04 UTC, bystam commented on auth/mvnw.cmd
> +exit /B %ERROR_CODE%
Right - true. Specifically having a maven wrapper, though, feels like a bit like something that's here but might mislead one to believe that this submodule is somehow built using its own maven version, which I'm pretty sure it definitely won't be.

2021-04-19 13:41 UTC, vonElfvin commented on auth/src/main/kotlin/com/hedvig/auth/services/UserService.kt
> +     */
All good points, as I said I'd prefer to have discussions with the whole backend team on the topic so we can evolve on this topic as a company. Last time we discussed it was like 1.5 years ago

2021-04-19 13:49 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/config/AxonConfig.java
> +          "com.hedvig.memberservice.users",
Ah yea that's a really good catch! I completely forgot about that 🤦

2021-04-19 14:04 UTC, niho commented
I've addressed all the feedback and fixed the failing build (I was wrong, it wasn't a cache issue as I suspected).

So this should be ready to merge, unless there is any more feedback on the changes I've made since after the review.

2021-04-21 09:01 UTC, bystam submitted a review, later dismissed
Really nice! 🚀

2021-04-21 10:05 UTC, bystam approved these changes

2021-04-22 10:02 UTC, bystam approved these changes
Looks great, though I suspect you will need to merge the second "repair" commit and revert it here to make it build upon merging.

I turned off the "auto-dissmiss approvals upon new commits" features so that you can consider this PR approved even after the final tweaks.

2021-04-22 11:19 UTC, niho commented
> [...] I suspect you will need to merge the second "repair" commit and revert it here to make it build upon merging.

I already did that with [the revert commit](https://github.com/HedvigInsurance/member-registry-service/pull/489/commits/cb07e42bec42dc0f3626923f0bf1f361c2387fd4). Or are we thinking of different things? 😕

2021-04-22 11:21 UTC, bystam commented
> > [...] I suspect you will need to merge the second "repair" commit and revert it here to make it build upon merging.
> 
> I already did that with [the revert commit](https://github.com/HedvigInsurance/member-registry-service/pull/489/commits/cb07e42bec42dc0f3626923f0bf1f361c2387fd4). Or are we thinking of different things? 😕

That was the first one that fixed members who were created from Rapio, I'm thinking about this one I merged this morning: https://github.com/HedvigInsurance/member-registry-service/pull/493

2021-04-22 11:26 UTC, niho commented
> > > [...] I suspect you will need to merge the second "repair" commit and revert it here to make it build upon merging.
> > 
> > 
> > I already did that with [the revert commit](https://github.com/HedvigInsurance/member-registry-service/pull/489/commits/cb07e42bec42dc0f3626923f0bf1f361c2387fd4). Or are we thinking of different things? 😕
> 
> That was the first one that fixed members who were created from Rapio, I'm thinking about this one I merged this morning: #493
> 
> But maybe I'm missing something?

Oh, I see. I think I deleted that as well in the merge commit. They turned up as a conflict when I merged with master and the names was so similar so I just assumed it was the same thing. 😝

2021-04-22 11:26 UTC, merged