Fix NPE and return value for unsign endpoint
HedvigInsurance/member-registry-service pull request #510
Opened 2021-05-26 10:27 UTC by tobiasbexelius

# Jira Issue: [MX-146]

## What?
- Fix NPE in unsign member endpoint when member for given ssn does not exist
- Fix return value so that true is only returned when something is deleted

## Why?
- 

## Optional checklist
- [ ] Unit tests written
- [x] Tested locally
- [x] Codescouted

[MX-146]: https://hedvig.atlassian.net/browse/MX-146

2021-05-26 15:38 UTC, vonElfvin reviewed
Cool! I could see a potential bug in the code we might want to look into 🙏

2021-05-26 15:38 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/services/QualityAssuranceService.kt
> +        if (signedMemberEntity.isPresent) {
Nice catch!!

🕵️‍♂️

2021-05-26 15:38 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/services/QualityAssuranceService.kt
>          val member = memberRepository.findBySsn(ssn).firstOrNull()
I think it's likely that this will find the wrong member. Since it might find a member with the same ssn that was not the one signed. Maybe @bystam can shed some light on that though?

2021-05-26 15:38 UTC, vonElfvin commented on member-service/src/main/java/com/hedvig/memberservice/services/QualityAssuranceService.kt
>          val member = memberRepository.findBySsn(ssn).firstOrNull()
Or we can delete all users for all members instead of the first one. Unsure what the risk is in that though, probably worth 🤷

2021-05-27 07:03 UTC, bystam commented on member-service/src/main/java/com/hedvig/memberservice/services/QualityAssuranceService.kt
>          val member = memberRepository.findBySsn(ssn).firstOrNull()
I guess we could use the `DeleteMember` command here, yes. That could probably even replace the "delete user" one because it will delete the user implicitly (but I guess not very obviously).

I don't think there's one super obvious answer here... the fact that we have many members with the same SSN makes several things non-obvious in this regard. Especially since the UI for "unsign" takes a personal number and not a member ID.

I think actually deleting members could cause "system state integrity" issues though. Other services won't know that the member is deleted, and they might rely upon it still.

I think Elvins proposal that we fetch **all** the members for an SSN value and delete all the users we find for those members is the most robust solution.

2021-05-27 07:04 UTC, bystam requested changes
I propose doing the change as suggested by Elvin: find **all** members based on SSN and delete all the users you find connected to it (should only be one, but that way we make sure we find it).

2021-05-27 09:24 UTC, tobiasbexelius commented
Fixed!

2021-05-27 09:32 UTC, bystam approved these changes
Awesome!

2021-05-27 09:40 UTC, merged